import type { Lesson } from "@/lib/learn";
import { REF } from "./references";

export const ACCOUNTING: Lesson[] = [
  {
    id: "three-statements",
    category: "accounting",
    order: 1,
    title: "The three financial statements",
    tagline: "Profit, position and cash in plain words",
    icon: "file",
    minutes: 3,
    legal: false,
    cards: [
      {
        icon: "trending",
        title: "Income statement: did we profit?",
        body: "Covers a period, such as a year. Revenue minus cost of sales gives gross profit. Subtract other expenses to get net profit.",
      },
      {
        icon: "scale",
        title: "Balance sheet: what we own and owe",
        body: "A snapshot on one date. It always balances: Assets = Liabilities + Equity. Equity is what would be left for the owners if all debts were paid.",
      },
      {
        icon: "coins",
        title: "Cash flow: where did the cash go?",
        body: "Shows cash in and out from operations, investing and financing. A business can show profit and still run out of cash if customers pay late.",
      },
    ],
    quiz: [
      {
        id: "q1",
        kind: "numeric",
        prompt: "A company has assets of LKR 5,000,000 and liabilities of LKR 3,000,000. What is its equity?",
        answer: 2000000,
        tolerance: 1,
        unit: "LKR",
        explanation: "Equity = Assets − Liabilities = 5,000,000 − 3,000,000 = LKR 2,000,000.",
      },
      {
        id: "q2",
        kind: "mcq",
        prompt: "Which statement is a snapshot on a single date?",
        options: [
          { id: "a", text: "Balance sheet" },
          { id: "b", text: "Income statement" },
          { id: "c", text: "Cash flow statement" },
        ],
        correctOptionId: "a",
        explanation: "The balance sheet shows position at one date; the other two cover a period.",
      },
      {
        id: "q3",
        kind: "numeric",
        prompt: "Revenue LKR 2,400,000, cost of sales LKR 1,400,000, other expenses LKR 600,000. What is net profit?",
        answer: 400000,
        tolerance: 1,
        unit: "LKR",
        explanation: "Gross profit = 1,000,000. Net profit = 1,000,000 − 600,000 = LKR 400,000.",
      },
      {
        id: "q4",
        kind: "mcq",
        prompt: "A shop is profitable but can't pay suppliers this month. Which statement best shows why?",
        options: [
          { id: "a", text: "Cash flow statement" },
          { id: "b", text: "Income statement" },
          { id: "c", text: "None of them" },
        ],
        correctOptionId: "a",
        explanation: "Profit isn't cash. The cash flow statement shows cash stuck in unpaid invoices or stock.",
      },
    ],
    references: [REF.slfrsSmes],
  },
  {
    id: "accruals-and-depreciation",
    category: "accounting",
    order: 2,
    title: "Accruals, depreciation and working capital",
    tagline: "Three ideas that confuse most new managers",
    icon: "calculator",
    minutes: 4,
    legal: false,
    cards: [
      {
        icon: "history",
        title: "Accrual accounting",
        body: "Record revenue when you earn it and expenses when you incur them, not when cash moves. Double-entry means every transaction touches at least two accounts.",
      },
      {
        icon: "truck",
        title: "Depreciation",
        body: "A van used for five years shouldn't hit profit all in year one. Straight-line depreciation spreads the cost: (cost − resale value) ÷ useful years.",
        example: "A LKR 6,000,000 van, 5 years, no resale value: LKR 1,200,000 a year.",
      },
      {
        icon: "wallet",
        title: "Working capital",
        body: "Working capital = current assets (cash, stock, money owed to you) − current liabilities (bills due within a year). Negative working capital is an early warning sign.",
      },
    ],
    quiz: [
      {
        id: "q1",
        kind: "numeric",
        prompt: "A van costs LKR 6,000,000, lasts 5 years and has no resale value. What is the yearly straight-line depreciation?",
        answer: 1200000,
        tolerance: 1,
        unit: "LKR",
        explanation: "6,000,000 ÷ 5 = LKR 1,200,000 a year.",
      },
      {
        id: "q2",
        kind: "mcq",
        prompt: "You complete a job in March and the client pays in May. Under accrual accounting, when is revenue recorded?",
        options: [
          { id: "a", text: "March" },
          { id: "b", text: "May" },
          { id: "c", text: "Split between both months" },
        ],
        correctOptionId: "a",
        explanation: "Revenue is recorded when earned (March). May's payment only reduces money owed to you.",
      },
      {
        id: "q3",
        kind: "numeric",
        prompt: "Current assets are LKR 3,500,000 and current liabilities are LKR 2,000,000. What is working capital?",
        answer: 1500000,
        tolerance: 1,
        unit: "LKR",
        explanation: "3,500,000 − 2,000,000 = LKR 1,500,000.",
      },
      {
        id: "q4",
        kind: "mcq",
        prompt: "You buy a van with cash. What happens to total assets on the balance sheet?",
        options: [
          { id: "a", text: "Unchanged: cash goes down, vehicles go up" },
          { id: "b", text: "They fall by the van's price" },
          { id: "c", text: "They rise by the van's price" },
        ],
        correctOptionId: "a",
        explanation: "One asset (cash) swaps for another (the van), so the total stays the same.",
      },
    ],
    references: [REF.slfrsSmes],
  },
  {
    id: "rules-in-sri-lanka",
    category: "accounting",
    order: 3,
    title: "Accounting rules in Sri Lanka",
    tagline: "Who sets the standards and what companies must do",
    icon: "scale",
    minutes: 3,
    legal: true,
    factsAsOf: "September 2026",
    cards: [
      {
        icon: "scale",
        title: "The Companies Act",
        body: "The Companies Act No. 7 of 2007 requires every company to keep proper accounting records and prepare financial statements. Records are normally kept in Sri Lanka.",
      },
      {
        icon: "book",
        title: "Who sets the standards",
        body: "The Institute of Chartered Accountants of Sri Lanka (CA Sri Lanka) issues Sri Lanka Accounting Standards, based on international standards. Many smaller companies can use the simpler SLFRS for SMEs.",
      },
      {
        icon: "landmark",
        title: "Register for tax early",
        body: "Under the Inland Revenue (Amendment) Act No. 11 of 2026, every company incorporated or registered in Sri Lanka must register with the Inland Revenue Department within 30 days.",
      },
    ],
    quiz: [
      {
        id: "q1",
        kind: "mcq",
        prompt: "Which law requires Sri Lankan companies to keep accounting records?",
        options: [
          { id: "a", text: "Companies Act No. 7 of 2007" },
          { id: "b", text: "Land (Restrictions on Alienation) Act" },
          { id: "c", text: "Monetary Law Act" },
        ],
        correctOptionId: "a",
        explanation: "The Companies Act sets the rules on accounting records, financial statements and audits.",
      },
      {
        id: "q2",
        kind: "mcq",
        prompt: "Who issues Sri Lanka's accounting standards?",
        options: [
          { id: "a", text: "CA Sri Lanka" },
          { id: "b", text: "Central Bank of Sri Lanka" },
          { id: "c", text: "Inland Revenue Department" },
        ],
        correctOptionId: "a",
        explanation: "CA Sri Lanka issues the standards; the IRD handles tax, and the Central Bank handles monetary policy.",
      },
      {
        id: "q3",
        kind: "mcq",
        prompt: "A new company is incorporated today. When must it register with the Inland Revenue Department?",
        options: [
          { id: "a", text: "Within 30 days" },
          { id: "b", text: "When it first makes a profit" },
          { id: "c", text: "Only if it registers for VAT" },
        ],
        correctOptionId: "a",
        explanation: "The 2026 amendment requires companies to register within 30 days of incorporation or registration.",
      },
      {
        id: "q4",
        kind: "mcq",
        prompt: "A small private company wants simpler reporting rules. What can it often use?",
        options: [
          { id: "a", text: "SLFRS for SMEs" },
          { id: "b", text: "No standards at all" },
          { id: "c", text: "Tax returns instead of accounts" },
        ],
        correctOptionId: "a",
        explanation: "SLFRS for SMEs is a lighter standard designed for smaller entities.",
      },
    ],
    references: [REF.companiesAct, REF.slfrsSmes, REF.irdNotice2026],
  },
];
