import type { Lesson } from "@/lib/learn";

export const CEO_MATH: Lesson[] = [
  {
    id: "roi-and-payback",
    category: "ceo-math",
    order: 1,
    title: "ROI and payback",
    tagline: "Is this investment worth it, and how fast?",
    icon: "percent",
    minutes: 3,
    legal: false,
    cards: [
      {
        icon: "percent",
        title: "ROI in one line",
        body: "Return on investment tells you how much you earned for every rupee you put in. ROI = (gain − cost) ÷ cost × 100.",
        example: "A LKR 200,000 delivery bike brings LKR 260,000 extra profit. ROI = 60,000 ÷ 200,000 = 30%.",
      },
      {
        icon: "history",
        title: "Payback period",
        body: "Payback tells you how long until the money comes back. Payback = cost ÷ cash gained per year. Shorter payback means less time at risk.",
        example: "A LKR 1,200,000 machine saves LKR 400,000 a year. Payback = 3 years.",
      },
      {
        icon: "crown",
        title: "Think like a CEO",
        body: "Never judge ROI alone. Compare it with safer options like a fixed deposit, check the risk, and watch the time: 30% over three years is only about 10% a year.",
      },
    ],
    quiz: [
      {
        id: "q1",
        kind: "numeric",
        prompt: "Your bakery spends LKR 500,000 on a new oven and earns LKR 650,000 extra profit from it. What is the ROI?",
        answer: 30,
        tolerance: 0.5,
        unit: "%",
        explanation: "Gain is 650,000 − 500,000 = 150,000. ROI = 150,000 ÷ 500,000 × 100 = 30%.",
      },
      {
        id: "q2",
        kind: "numeric",
        prompt: "Solar panels cost LKR 1,800,000 and cut electricity bills by LKR 450,000 a year. What is the payback period?",
        answer: 4,
        tolerance: 0.05,
        unit: "years",
        explanation: "Payback = 1,800,000 ÷ 450,000 = 4 years.",
      },
      {
        id: "q3",
        kind: "numeric",
        prompt: "A marketing campaign costs LKR 80,000 and brings LKR 60,000 extra profit. What is the ROI?",
        answer: -25,
        tolerance: 0.5,
        unit: "%",
        explanation: "Gain is 60,000 − 80,000 = −20,000. ROI = −20,000 ÷ 80,000 × 100 = −25%. Negative ROI means you lost money.",
      },
      {
        id: "q4",
        kind: "mcq",
        prompt: "Project A earns 25% ROI in one year. Project B earns 40% ROI over four years. Which earns more per year?",
        options: [
          { id: "a", text: "Project A" },
          { id: "b", text: "Project B" },
          { id: "c", text: "They are the same" },
        ],
        correctOptionId: "a",
        explanation: "Project B is roughly 10% a year (40% ÷ 4), far below Project A's 25%.",
      },
      {
        id: "q5",
        kind: "mcq",
        prompt: "Two projects both promise 20% ROI. What should you check next?",
        options: [
          { id: "a", text: "Risk and how long the money is tied up" },
          { id: "b", text: "Which team has nicer slides" },
          { id: "c", text: "Nothing; they are equal" },
        ],
        correctOptionId: "a",
        explanation: "Same ROI can hide very different risk and timing. A safer, faster project usually wins.",
      },
    ],
    references: [],
  },
  {
    id: "margins-and-break-even",
    category: "ceo-math",
    order: 2,
    title: "Margins and break-even",
    tagline: "How many sales before you stop losing money?",
    icon: "target",
    minutes: 3,
    legal: false,
    cards: [
      {
        icon: "coins",
        title: "Gross vs net margin",
        body: "Gross margin = (price − cost to make) ÷ price. It shows how much each sale leaves. Net margin = profit after all expenses ÷ revenue. It shows what the whole business keeps.",
      },
      {
        icon: "target",
        title: "Break-even point",
        body: "Fixed costs (rent, salaries) stay the same however much you sell. Each sale contributes price minus variable cost. Break-even units = fixed costs ÷ contribution per unit.",
        example: "Kottu at LKR 1,000, ingredients LKR 400, fixed costs LKR 300,000 a month: break-even = 300,000 ÷ 600 = 500 plates.",
      },
      {
        icon: "crown",
        title: "Think like a CEO",
        body: "High gross margin with low net margin means overheads are eating profit. To break even sooner: raise price, cut variable cost, or trim fixed costs.",
      },
    ],
    quiz: [
      {
        id: "q1",
        kind: "numeric",
        prompt: "A cup of tea sells for LKR 250 and costs LKR 100 to make. What is the gross margin?",
        answer: 60,
        tolerance: 0.5,
        unit: "%",
        explanation: "(250 − 100) ÷ 250 × 100 = 60%.",
      },
      {
        id: "q2",
        kind: "numeric",
        prompt: "Fixed costs are LKR 600,000 a month. Each T-shirt sells for LKR 2,000 and costs LKR 1,200 to make. How many T-shirts to break even?",
        answer: 750,
        tolerance: 0.5,
        unit: "units",
        explanation: "Contribution = 2,000 − 1,200 = 800. Break-even = 600,000 ÷ 800 = 750 T-shirts.",
      },
      {
        id: "q3",
        kind: "numeric",
        prompt: "Revenue is LKR 10,000,000 and total expenses are LKR 8,500,000. What is the net margin?",
        answer: 15,
        tolerance: 0.5,
        unit: "%",
        explanation: "Profit = 1,500,000. Net margin = 1,500,000 ÷ 10,000,000 × 100 = 15%.",
      },
      {
        id: "q4",
        kind: "mcq",
        prompt: "Gross margin is 70%, but the company still loses money. What is the most likely cause?",
        options: [
          { id: "a", text: "Overheads like rent and salaries are too high" },
          { id: "b", text: "Prices are too high" },
          { id: "c", text: "Products cost too little to make" },
        ],
        correctOptionId: "a",
        explanation: "Each sale is profitable, so the losses come from fixed costs below the gross profit line.",
      },
    ],
    references: [],
  },
  {
    id: "unit-economics",
    category: "ceo-math",
    order: 3,
    title: "Customer unit economics",
    tagline: "What a customer costs versus what they bring",
    icon: "user",
    minutes: 3,
    legal: false,
    cards: [
      {
        icon: "tag",
        title: "CAC: cost to win a customer",
        body: "Customer acquisition cost = sales and marketing spend ÷ new customers won in that period.",
        example: "LKR 300,000 on ads brings 150 new customers. CAC = LKR 2,000.",
      },
      {
        icon: "heart",
        title: "LTV: what a customer is worth",
        body: "Lifetime value = profit per customer per month × months they stay. When customers leave faster (higher churn), LTV drops.",
        example: "LKR 1,500 profit a month for 12 months = LKR 18,000 LTV.",
      },
      {
        icon: "crown",
        title: "Think like a CEO",
        body: "A common rule of thumb is LTV at least 3× CAC. Below 1×, every new customer loses money, so growing faster only loses money faster.",
      },
    ],
    quiz: [
      {
        id: "q1",
        kind: "numeric",
        prompt: "You spent LKR 300,000 on ads and won 150 new customers. What is your CAC?",
        answer: 2000,
        tolerance: 0.5,
        unit: "LKR",
        explanation: "CAC = 300,000 ÷ 150 = LKR 2,000 per customer.",
      },
      {
        id: "q2",
        kind: "numeric",
        prompt: "A customer brings LKR 1,500 profit a month and stays 12 months. What is their LTV?",
        answer: 18000,
        tolerance: 0.5,
        unit: "LKR",
        explanation: "LTV = 1,500 × 12 = LKR 18,000.",
      },
      {
        id: "q3",
        kind: "numeric",
        prompt: "LTV is LKR 18,000 and CAC is LKR 6,000. What is the LTV:CAC ratio?",
        answer: 3,
        tolerance: 0.01,
        unit: "×",
        explanation: "18,000 ÷ 6,000 = 3×, right at the common healthy benchmark.",
      },
      {
        id: "q4",
        kind: "mcq",
        prompt: "Your LTV:CAC ratio is 0.8. What is the best move?",
        options: [
          { id: "a", text: "Fix retention or cut acquisition cost before scaling" },
          { id: "b", text: "Double the ad budget to grow faster" },
          { id: "c", text: "Ignore it; revenue is growing" },
        ],
        correctOptionId: "a",
        explanation: "At 0.8×, each customer costs more than they return. Scaling multiplies the losses.",
      },
    ],
    references: [],
  },
];
