import type { Lesson } from "@/lib/learn";
import { REF } from "./references";

export const INVESTING: Lesson[] = [
  {
    id: "stock-market-basics",
    category: "investing",
    order: 1,
    title: "Stock market 101: the CSE",
    tagline: "How to own a slice of a Sri Lankan company",
    icon: "trending",
    minutes: 4,
    legal: true,
    factsAsOf: "September 2026",
    cards: [
      {
        icon: "landmark",
        title: "One exchange, one regulator",
        body: "The Colombo Stock Exchange (CSE) runs Sri Lanka's only stock market. The Securities and Exchange Commission (SEC) licenses stockbrokers and oversees the market to protect investors.",
      },
      {
        icon: "user",
        title: "Your ticket in: a CDS account",
        body: "To buy shares, open a Central Depository System (CDS) account through a licensed stockbroker or custodian bank. Your shares are held there electronically, so there are no paper certificates to lose.",
      },
      {
        icon: "history",
        title: "Trade today, settle in two days",
        body: "You place buy or sell orders through your broker. Since June 2024, CSE share trades settle on T+2: money and shares change hands two market days after the trade.",
      },
      {
        icon: "coins",
        title: "Two ways to earn",
        body: "Dividends are a share of company profits; 15% tax is withheld before you receive them. Capital gains come from selling higher than you bought. Prices can also fall, so invest money you won't need soon.",
      },
      {
        icon: "shield",
        title: "Don't put all eggs in one basket",
        body: "Spread your money across several companies and sectors, or buy a unit trust that does it for you. Index figures like the ASPI show how the whole market is moving.",
      },
    ],
    quiz: [
      {
        id: "q1",
        kind: "mcq",
        prompt: "What do you need before buying shares on the CSE?",
        options: [
          { id: "a", text: "A CDS account opened through a licensed stockbroker" },
          { id: "b", text: "A registered company" },
          { id: "c", text: "A foreign bank account" },
        ],
        correctOptionId: "a",
        explanation: "Shares are held electronically in your CDS account, opened through a broker or custodian bank.",
      },
      {
        id: "q2",
        kind: "mcq",
        prompt: "You buy shares on a Monday with no holidays that week. Under T+2, when does the trade settle?",
        options: [
          { id: "a", text: "Monday" },
          { id: "b", text: "Tuesday" },
          { id: "c", text: "Wednesday" },
          { id: "d", text: "Friday" },
        ],
        correctOptionId: "c",
        explanation: "T+2 means two market days after the trade date: Monday + 2 = Wednesday.",
      },
      {
        id: "q3",
        kind: "numeric",
        prompt: "You are due a dividend of LKR 20,000 before tax. With 15% withheld, how much reaches your account?",
        answer: 17000,
        tolerance: 0.5,
        unit: "LKR",
        explanation: "Tax withheld = 20,000 × 15% = 3,000. You receive 20,000 − 3,000 = LKR 17,000.",
      },
      {
        id: "q4",
        kind: "numeric",
        prompt: "You buy 100 shares at LKR 50 and sell them at LKR 65. What is your gain before fees?",
        answer: 1500,
        tolerance: 0.5,
        unit: "LKR",
        explanation: "Gain per share is 15. 15 × 100 shares = LKR 1,500.",
      },
      {
        id: "q5",
        kind: "mcq",
        prompt: "Which is the best way to lower risk as a new investor?",
        options: [
          { id: "a", text: "Spread money across companies and sectors" },
          { id: "b", text: "Buy only last week's top-rising stock" },
          { id: "c", text: "Borrow money to buy more shares" },
        ],
        correctOptionId: "a",
        explanation: "Diversification means one company's bad news can't wipe you out.",
      },
    ],
    references: [REF.secGuide, REF.cseT2, REF.irdTaxChart],
  },
  {
    id: "deposits-bills-and-gold",
    category: "investing",
    order: 2,
    title: "Safe havens: FDs, T-bills and gold",
    tagline: "Where to park money you can't afford to lose",
    icon: "shield",
    minutes: 4,
    legal: true,
    factsAsOf: "September 2026",
    cards: [
      {
        icon: "wallet",
        title: "Fixed deposits",
        body: "A fixed deposit lends your money to a bank or finance company for a set time at a set rate. Since April 2025, 10% tax is withheld on interest. If you have no taxable income, you may submit a self-declaration instead.",
      },
      {
        icon: "shield",
        title: "Deposit insurance has a limit",
        body: "If a licensed bank or finance company fails, the Sri Lanka Deposit Insurance Scheme pays up to LKR 1.1 million per depositor, per institution. Anything above that is not covered.",
      },
      {
        icon: "landmark",
        title: "Treasury bills and bonds",
        body: "These are loans to the Government, managed by the Central Bank. T-bills last 91, 182 or 364 days and are sold at a discount: you pay less and receive full face value at the end. Bonds last 2 to 30 years.",
      },
      {
        icon: "gem",
        title: "Gold",
        body: "Gold pays no interest or dividends. Its world price is set in US dollars, so a weaker rupee pushes the local price up. Jewellery includes making charges you usually lose when selling.",
      },
      {
        icon: "target",
        title: "Match the tool to the goal",
        body: "Emergency fund: savings or a short FD. Money needed on a known date: T-bills. Long-term growth: shares. Protection against a falling rupee: a small slice of gold.",
      },
    ],
    quiz: [
      {
        id: "q1",
        kind: "numeric",
        prompt: "A LKR 1,000,000 fixed deposit pays 8% a year. How much interest do you receive after 10% withholding tax?",
        answer: 72000,
        tolerance: 0.5,
        unit: "LKR",
        explanation: "Interest = 1,000,000 × 8% = 80,000. Tax withheld = 8,000. You receive LKR 72,000.",
      },
      {
        id: "q2",
        kind: "mcq",
        prompt: "You keep LKR 3 million in one finance company and it fails. How much does deposit insurance cover?",
        options: [
          { id: "a", text: "LKR 3 million" },
          { id: "b", text: "Up to LKR 1.1 million" },
          { id: "c", text: "Nothing" },
        ],
        correctOptionId: "b",
        explanation: "Cover is capped at LKR 1.1 million per depositor, per institution. Spreading savings across institutions reduces the risk.",
      },
      {
        id: "q3",
        kind: "numeric",
        prompt: "You buy a T-bill with LKR 100,000 face value for LKR 97,500. What do you earn at maturity before tax?",
        answer: 2500,
        tolerance: 0.5,
        unit: "LKR",
        explanation: "You receive the full LKR 100,000, so you earn 100,000 − 97,500 = LKR 2,500.",
      },
      {
        id: "q4",
        kind: "mcq",
        prompt: "World gold prices stay flat, but gold gets more expensive in Colombo. Why?",
        options: [
          { id: "a", text: "The rupee weakened against the US dollar" },
          { id: "b", text: "Banks raised FD rates" },
          { id: "c", text: "The CSE index fell" },
        ],
        correctOptionId: "a",
        explanation: "Gold is priced in dollars, so each dollar of gold costs more rupees when the rupee weakens.",
      },
      {
        id: "q5",
        kind: "mcq",
        prompt: "What is the best place for your emergency fund?",
        options: [
          { id: "a", text: "A savings account or short fixed deposit" },
          { id: "b", text: "Gold jewellery" },
          { id: "c", text: "Shares in one company" },
        ],
        correctOptionId: "a",
        explanation: "Emergency money must be safe and quick to access. Shares and jewellery can lose value right when you need cash.",
      },
    ],
    references: [REF.cbslDepositInsurance, REF.cbslGovSecurities, REF.irdTaxChart, REF.irdNotice2026],
  },
  {
    id: "compounding-and-inflation",
    category: "investing",
    order: 3,
    title: "Compounding and inflation",
    tagline: "Why time is your best investing partner",
    icon: "rocket",
    minutes: 3,
    legal: false,
    cards: [
      {
        icon: "rocket",
        title: "Interest on interest",
        body: "Compounding means your returns start earning returns. Value after n years = starting amount × (1 + rate)ⁿ.",
        example: "LKR 100,000 at 10% becomes 110,000 after one year and 121,000 after two.",
      },
      {
        icon: "zap",
        title: "The rule of 72",
        body: "A quick mental trick: years to double your money ≈ 72 ÷ yearly return. At 8%, money doubles in about 9 years.",
      },
      {
        icon: "flame",
        title: "Inflation eats returns",
        body: "If prices rise faster than your savings, you are getting poorer. Real return ≈ your return − inflation. A 9% FD with 5% inflation grows your buying power by only about 4%.",
      },
    ],
    quiz: [
      {
        id: "q1",
        kind: "numeric",
        prompt: "LKR 100,000 grows 10% a year, compounded. What is it worth after 2 years?",
        answer: 121000,
        tolerance: 1,
        unit: "LKR",
        explanation: "100,000 × 1.1 × 1.1 = LKR 121,000.",
      },
      {
        id: "q2",
        kind: "numeric",
        prompt: "Using the rule of 72, roughly how many years does money take to double at 12% a year?",
        answer: 6,
        tolerance: 0.1,
        unit: "years",
        explanation: "72 ÷ 12 = 6 years.",
      },
      {
        id: "q3",
        kind: "numeric",
        prompt: "Your deposit pays 9% a year and inflation is 5%. What is your approximate real return?",
        answer: 4,
        tolerance: 0.2,
        unit: "%",
        explanation: "Real return ≈ 9% − 5% = 4%.",
      },
      {
        id: "q4",
        kind: "mcq",
        prompt: "Why does starting to invest 10 years earlier make such a big difference?",
        options: [
          { id: "a", text: "Compounding has more years to work" },
          { id: "b", text: "Banks pay young people higher rates" },
          { id: "c", text: "Taxes are lower early on" },
        ],
        correctOptionId: "a",
        explanation: "Growth builds on growth, so the final years add the most. Extra years matter more than extra rupees.",
      },
    ],
    references: [REF.investorGovCompound],
  },
];
