import type { Lesson } from "@/lib/learn";
import { REF } from "./references";

export const REAL_ESTATE: Lesson[] = [
  {
    id: "buying-property",
    category: "real-estate",
    order: 1,
    title: "Buying property in Sri Lanka",
    tagline: "Title, deeds, stamp duty and foreign buyers",
    icon: "house",
    minutes: 4,
    legal: true,
    factsAsOf: "September 2026",
    cards: [
      {
        icon: "file",
        title: "Check the title first",
        body: "Before paying anything, have a lawyer trace the deed history at the Land Registry and confirm the survey plan matches the land you are buying. Most property disputes start with a weak title.",
      },
      {
        icon: "scale",
        title: "The deed makes it official",
        body: "A property sale is done through a deed of transfer signed before a notary public, then registered at the Land Registry. Under the 2026 tax amendment, registering land or title is being tied to having a Taxpayer Identification Number (TIN).",
      },
      {
        icon: "receipt",
        title: "Stamp duty",
        body: "The buyer pays stamp duty to the Provincial Council where the property is: 3% on the first LKR 100,000 and 4% on the balance of the property's value.",
      },
      {
        icon: "user",
        title: "Foreign buyers",
        body: "Foreigners generally cannot buy land in Sri Lanka. They can buy a condominium apartment if the full price is paid through an inward foreign remittance before the deed is signed.",
      },
    ],
    quiz: [
      {
        id: "q1",
        kind: "numeric",
        prompt: "You buy a house for LKR 20,000,000. Stamp duty is 3% on the first LKR 100,000 and 4% on the rest. How much do you pay?",
        answer: 799000,
        tolerance: 1,
        unit: "LKR",
        explanation: "3% × 100,000 = 3,000. 4% × 19,900,000 = 796,000. Total = LKR 799,000.",
      },
      {
        id: "q2",
        kind: "mcq",
        prompt: "Who normally pays stamp duty on a property transfer?",
        options: [
          { id: "a", text: "The buyer" },
          { id: "b", text: "The seller" },
          { id: "c", text: "The notary" },
        ],
        correctOptionId: "a",
        explanation: "The buyer pays stamp duty to the Provincial Council for the area where the property is.",
      },
      {
        id: "q3",
        kind: "mcq",
        prompt: "A foreign friend wants to buy property in Colombo. What can they buy?",
        options: [
          { id: "a", text: "A condominium apartment paid by inward remittance" },
          { id: "b", text: "Freehold land for a house" },
          { id: "c", text: "Nothing at all" },
        ],
        correctOptionId: "a",
        explanation: "Condominium units are exempt from the land ownership restriction when fully paid through an inward foreign remittance.",
      },
      {
        id: "q4",
        kind: "mcq",
        prompt: "What should happen before you pay for a plot of land?",
        options: [
          { id: "a", text: "A lawyer checks the title history and survey plan" },
          { id: "b", text: "You pay a deposit to hold it" },
          { id: "c", text: "You start building to secure it" },
        ],
        correctOptionId: "a",
        explanation: "Title and survey checks protect you from buying land the seller doesn't fully own.",
      },
    ],
    references: [REF.stampDuty, REF.landRestrictionsAct, REF.condoForeigners, REF.irdNotice2026],
  },
  {
    id: "rental-yield-and-selling",
    category: "real-estate",
    order: 2,
    title: "Rental yield and selling",
    tagline: "Is a rental property a good investment?",
    icon: "wallet",
    minutes: 4,
    legal: true,
    factsAsOf: "September 2026",
    cards: [
      {
        icon: "percent",
        title: "Gross yield",
        body: "Gross rental yield = yearly rent ÷ property price × 100. It is the quickest way to compare a rental with a fixed deposit.",
        example: "A LKR 25,000,000 flat renting at LKR 125,000 a month earns 1,500,000 a year: a 6% gross yield.",
      },
      {
        icon: "receipt",
        title: "Net yield is what you keep",
        body: "Subtract yearly costs such as maintenance, repairs, insurance and empty months. Net yield = (yearly rent − yearly costs) ÷ price × 100.",
      },
      {
        icon: "landmark",
        title: "Tax when you sell",
        body: "A gain on selling land or buildings is taxed as capital gains tax: 15% for individuals from 3 June 2026 and 30% for companies. Tax and return are due within 30 days after the end of the month of sale.",
      },
      {
        icon: "house",
        title: "Your home may be exempt",
        body: "Selling your main home can be excluded from capital gains tax if you owned it for at least 3 years and lived in it for at least 2 of those years.",
      },
    ],
    quiz: [
      {
        id: "q1",
        kind: "numeric",
        prompt: "An apartment costs LKR 25,000,000 and rents for LKR 125,000 a month. What is the gross yield?",
        answer: 6,
        tolerance: 0.05,
        unit: "%",
        explanation: "Yearly rent = 1,500,000. Yield = 1,500,000 ÷ 25,000,000 × 100 = 6%.",
      },
      {
        id: "q2",
        kind: "numeric",
        prompt: "The same apartment has LKR 300,000 of yearly costs. What is the net yield?",
        answer: 4.8,
        tolerance: 0.05,
        unit: "%",
        explanation: "(1,500,000 − 300,000) ÷ 25,000,000 × 100 = 4.8%.",
      },
      {
        id: "q3",
        kind: "numeric",
        prompt: "In 2026 you sell a plot of land (not your home) at a LKR 4,000,000 gain. Ignoring small exemptions, how much capital gains tax at 15%?",
        answer: 600000,
        tolerance: 1,
        unit: "LKR",
        explanation: "4,000,000 × 15% = LKR 600,000.",
      },
      {
        id: "q4",
        kind: "mcq",
        prompt: "A fixed deposit pays 9%. A flat's net rental yield is 4%. What must the flat deliver to be worth it?",
        options: [
          { id: "a", text: "Price growth that makes up the gap" },
          { id: "b", text: "Nothing; property is always better" },
          { id: "c", text: "Lower stamp duty" },
        ],
        correctOptionId: "a",
        explanation: "The flat earns 5% less income a year, so it needs enough price growth to beat the safer FD.",
      },
      {
        id: "q5",
        kind: "mcq",
        prompt: "Which sale may be excluded from capital gains tax?",
        options: [
          { id: "a", text: "Your home, owned 3+ years and lived in for 2" },
          { id: "b", text: "A rental flat you owned for 1 year" },
          { id: "c", text: "Land bought last month" },
        ],
        correctOptionId: "a",
        explanation: "IRD excludes a principal residence meeting the ownership and occupation conditions.",
      },
    ],
    references: [REF.irdNotice2026, REF.irdCgt],
  },
];
