import type { Lesson } from "@/lib/learn";
import { REF } from "./references";

export const TAX: Lesson[] = [
  {
    id: "corporate-income-tax",
    category: "tax",
    order: 1,
    title: "Corporate income tax basics",
    tagline: "Rates, tax year and key deadlines",
    icon: "landmark",
    minutes: 4,
    legal: true,
    factsAsOf: "September 2026",
    cards: [
      {
        icon: "history",
        title: "The tax year",
        body: "Sri Lanka's year of assessment runs from 1 April to 31 March. Company income tax falls under the Inland Revenue Act No. 24 of 2017 and is collected by the Inland Revenue Department (IRD).",
      },
      {
        icon: "percent",
        title: "The headline rate",
        body: "Most companies pay 30% on taxable income. Betting and gaming, and liquor and tobacco businesses pay 45%. Taxable income is not the same as accounting profit, because some expenses aren't deductible.",
      },
      {
        icon: "receipt",
        title: "Pay as you go",
        body: "Tax is paid in four quarterly instalments by 15 August, 15 November, 15 February and 15 May. Any balance is due by 30 September, and the return by 30 November after the year ends.",
      },
      {
        icon: "coins",
        title: "Big cash payments cost you",
        body: "Paying LKR 500,000 or more in cash, instead of by bank transfer, card or account-payee cheque, means that payment can't be deducted as a business expense.",
      },
    ],
    quiz: [
      {
        id: "q1",
        kind: "numeric",
        prompt: "A trading company has taxable income of LKR 10,000,000 at the standard rate. How much income tax does it owe?",
        answer: 3000000,
        tolerance: 1,
        unit: "LKR",
        explanation: "10,000,000 × 30% = LKR 3,000,000.",
      },
      {
        id: "q2",
        kind: "numeric",
        prompt: "Instalments are based on last year's tax of LKR 4,000,000. If split evenly, how much is each quarterly instalment?",
        answer: 1000000,
        tolerance: 1,
        unit: "LKR",
        explanation: "4,000,000 ÷ 4 = LKR 1,000,000 per quarter.",
      },
      {
        id: "q3",
        kind: "mcq",
        prompt: "When is the income tax return for the 2025/26 year of assessment due?",
        options: [
          { id: "a", text: "31 March 2026" },
          { id: "b", text: "30 September 2026" },
          { id: "c", text: "30 November 2026" },
        ],
        correctOptionId: "c",
        explanation: "The IRD 2026 tax calendar lists 30 November 2026 for Y/A 2025/26 returns. The final payment is due earlier, on 30 September.",
      },
      {
        id: "q4",
        kind: "mcq",
        prompt: "Your company pays a supplier LKR 600,000 in cash. What is the tax effect?",
        options: [
          { id: "a", text: "It can't be deducted as a business expense" },
          { id: "b", text: "It is deductible as normal" },
          { id: "c", text: "It gets double deduction" },
        ],
        correctOptionId: "a",
        explanation: "Cash payments of LKR 500,000 or more outside approved methods are not deductible.",
      },
      {
        id: "q5",
        kind: "mcq",
        prompt: "Which business pays the higher 45% income tax rate?",
        options: [
          { id: "a", text: "A liquor or tobacco business" },
          { id: "b", text: "A software startup" },
          { id: "c", text: "A bakery" },
        ],
        correctOptionId: "a",
        explanation: "Betting and gaming, liquor and tobacco are taxed at 45%; most other companies pay 30%.",
      },
    ],
    references: [REF.irdTaxChart, REF.irdTaxCalendar2026, REF.irdNotice2026],
  },
  {
    id: "vat-and-sscl",
    category: "tax",
    order: 2,
    title: "VAT and SSCL",
    tagline: "The taxes added on sales and turnover",
    icon: "receipt",
    minutes: 4,
    legal: true,
    factsAsOf: "September 2026",
    cards: [
      {
        icon: "receipt",
        title: "How VAT works",
        body: "VAT is added to the price of most goods and services. A registered business collects VAT from customers, subtracts VAT it paid on purchases (input tax), and pays the difference to the IRD.",
      },
      {
        icon: "percent",
        title: "Rate and registration",
        body: "The standard VAT rate is 18%, effective 1 January 2024. You must register if taxable supplies exceed LKR 15 million in a quarter or LKR 60 million in a year.",
      },
      {
        icon: "landmark",
        title: "SSCL: a levy on turnover",
        body: "The Social Security Contribution Levy is 2.5% of liable turnover for importers, manufacturers, service providers and traders. Registration applies above LKR 15 million in a quarter or LKR 60 million over four quarters.",
      },
      {
        icon: "history",
        title: "Monthly rhythm",
        body: "VAT and SSCL payments for a month are due by the 20th of the next month. Monthly VAT returns are due by the end of the next month.",
      },
    ],
    quiz: [
      {
        id: "q1",
        kind: "numeric",
        prompt: "You sell a service for LKR 100,000 before VAT. How much VAT do you charge at 18%?",
        answer: 18000,
        tolerance: 0.5,
        unit: "LKR",
        explanation: "100,000 × 18% = LKR 18,000, so the customer pays LKR 118,000.",
      },
      {
        id: "q2",
        kind: "numeric",
        prompt: "This month you collected LKR 540,000 VAT on sales and paid LKR 360,000 VAT on purchases. How much VAT do you pay the IRD?",
        answer: 180000,
        tolerance: 1,
        unit: "LKR",
        explanation: "Output VAT − input VAT = 540,000 − 360,000 = LKR 180,000.",
      },
      {
        id: "q3",
        kind: "mcq",
        prompt: "Your yearly taxable supplies are LKR 45 million, never above LKR 15 million in any quarter. Must you register for VAT?",
        options: [
          { id: "a", text: "No, you are below both thresholds" },
          { id: "b", text: "Yes, every business must register" },
          { id: "c", text: "Yes, because you exceed LKR 36 million" },
        ],
        correctOptionId: "a",
        explanation: "Registration is required above LKR 60 million a year or LKR 15 million a quarter.",
      },
      {
        id: "q4",
        kind: "numeric",
        prompt: "Your liable turnover for SSCL this month is LKR 20,000,000. How much SSCL is due at 2.5%?",
        answer: 500000,
        tolerance: 1,
        unit: "LKR",
        explanation: "20,000,000 × 2.5% = LKR 500,000.",
      },
      {
        id: "q5",
        kind: "mcq",
        prompt: "By when must you pay VAT for the month of August?",
        options: [
          { id: "a", text: "20 September" },
          { id: "b", text: "31 August" },
          { id: "c", text: "30 November" },
        ],
        correctOptionId: "a",
        explanation: "VAT payments are due by the 20th of the following month.",
      },
    ],
    references: [REF.irdVat, REF.irdSscl, REF.irdTaxCalendar2026],
  },
  {
    id: "withholding-and-capital-gains",
    category: "tax",
    order: 3,
    title: "Withholding tax and capital gains",
    tagline: "Tax taken at source, and tax when you sell assets",
    icon: "coins",
    minutes: 4,
    legal: true,
    factsAsOf: "September 2026",
    cards: [
      {
        icon: "coins",
        title: "Withholding tax",
        body: "For some payments, the payer deducts tax before paying you and sends it to the IRD. Common rates: 10% on interest and 15% on dividends. The payer must give you a withholding certificate free of charge.",
      },
      {
        icon: "briefcase",
        title: "Service fees and rent",
        body: "5% is withheld on service fees paid to resident individuals, such as IT specialists or consultants, when monthly payments exceed LKR 100,000. Rent above LKR 100,000 a month has 10% withheld.",
      },
      {
        icon: "house",
        title: "Capital gains tax",
        body: "Gains from selling investment assets such as land or buildings are taxed at 15% for individuals and partnerships from 3 June 2026, and 30% for companies. File and pay within 30 days after the end of the month of sale.",
      },
      {
        icon: "shield",
        title: "What's excluded",
        body: "The IRD excludes a principal residence meeting its ownership and occupation conditions, and shares quoted on the Colombo Stock Exchange.",
      },
    ],
    quiz: [
      {
        id: "q1",
        kind: "numeric",
        prompt: "A company pays you a LKR 50,000 dividend. How much withholding tax is deducted at 15%?",
        answer: 7500,
        tolerance: 0.5,
        unit: "LKR",
        explanation: "50,000 × 15% = LKR 7,500. You receive LKR 42,500.",
      },
      {
        id: "q2",
        kind: "numeric",
        prompt: "Your company pays a resident IT consultant LKR 200,000 this month. How much withholding tax must it deduct at 5%?",
        answer: 10000,
        tolerance: 0.5,
        unit: "LKR",
        explanation: "The payment is above LKR 100,000, so 5% applies: 200,000 × 5% = LKR 10,000.",
      },
      {
        id: "q3",
        kind: "numeric",
        prompt: "Your company sells land at a LKR 10,000,000 gain. How much capital gains tax is due at the company rate?",
        answer: 3000000,
        tolerance: 1,
        unit: "LKR",
        explanation: "Companies pay 30%: 10,000,000 × 30% = LKR 3,000,000.",
      },
      {
        id: "q4",
        kind: "mcq",
        prompt: "You sell land on 10 July 2026. When are the capital gains tax return and payment due?",
        options: [
          { id: "a", text: "By 30 August 2026" },
          { id: "b", text: "By 10 August 2026" },
          { id: "c", text: "By 30 November 2027" },
        ],
        correctOptionId: "a",
        explanation: "Due within 30 days after the end of the month of sale: July ends on the 31st, so 30 August.",
      },
      {
        id: "q5",
        kind: "mcq",
        prompt: "Which gain is excluded from capital gains tax?",
        options: [
          { id: "a", text: "Selling shares quoted on the CSE" },
          { id: "b", text: "Selling a rental building" },
          { id: "c", text: "Selling an empty plot of land" },
        ],
        correctOptionId: "a",
        explanation: "IRD lists quoted CSE shares as excluded from capital gains tax.",
      },
    ],
    references: [REF.irdTaxChart, REF.irdNotice2026, REF.irdCgt],
  },
];
